# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8ae666789a1d7848840bc6f09edb2dcd43c6ff7528bd81bdf861fd04f743a0039bee3c462d21dc0151e9b0bdc25aded03b255906ef57b0b75559ed882e5be39

test:
  secret_key_base: 30ba97686a3122ba97696c1e69f2a46ecfa24e52bd49b0b1c675b5b8c5b3dce22fb4a6804cf2766a70e939df0e9f61d3257282aabd3e2018a7cd2f3454eb761d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
